version: "2.1"
services:
  jupyter:
    image: jupyter/tensorflow-notebook:latest
    restart: "no"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - "8888:8888"
    environment:
      NB_UID: ${UID}
      NB_GID: ${GID}